app = "n8n-for-sto"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  N8N_EDITOR_BASE_URL = "https://n8n-for-sto.fly.dev"
  N8N_TUNNEL = "true"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[deploy]
  strategy = "rolling"

[machines]
  memory = "512mb"
  cpus = 1
  count = 1
